# Generated by Django 5.1.7 on 2025-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('who', models.CharField(blank=True, max_length=255)),
                ('what', models.TextField(blank=True)),
                ('where', models.CharField(blank=True, max_length=255)),
                ('when', models.CharField(blank=True, max_length=255)),
                ('why_now', models.TextField(blank=True)),
                ('r1_as_is', models.TextField(blank=True)),
                ('r2_to_be', models.TextField(blank=True)),
                ('gap', models.TextField(blank=True)),
                ('problem_type', models.CharField(blank=True, choices=[('challenge', 'Вызов'), ('failure', 'Сбой')], max_length=50)),
                ('key_question', models.TextField(blank=True)),
            ],
        ),
    ]
